### ISSUE TITLE
/theme does not exist and background is not changed

### ISSUE THREAD

**Issue by Horosphere** [reorr/xfcolorizer#2]
I followed the steps for installing xfcolorizer. When I execute it on a wallpaper, it shows:

`Rendering /home/hsv/.themes/xfcolorize/gtk-3.0/assets/toggle-on-hover@2.png
Appliying theme
Property "/theme" does not exist on channel "xfce4-notifyd". If a new property should be created, use the --create option.
Restarting panel
`

The theme is applied, but the background is changed to a solid color and all titles blend into the background:
![xfcolorize](https://user-images.githubusercontent.com/18667015/32504470-df7ef646-c3ad-11e7-890b-ae25b5c9ede6.png)

**Comment by Horosphere** [comment]
Addendum:

It seems like that (using -w "color")  the style is correctly applied, but the window manager theme is broken in the sense that the title vanishes and the buttons are not replaced. Moreover, the background is also not replaced.

**Comment by reorr** [comment]
can you tell me witch version of xfce4-notifyd-config you use?
because in 0.3.6 version that i use there is /theme property on channel xfce4-notifyd, or you can add /theme property yourself from xfce4-settings-editor.

for the theme, the title in title bar is blended with title bar color like you can see in the example. so it's not like it's broken.

my bad the wallpaper doesn't change, but i've fixed it the latest commit and you must run xfcolorizer.py from xfcolorizer folder or it doesn't work properly

**Comment by Horosphere** [comment]
I am using version 0.4.0 of xfce4-notifyd.

I added the /theme property and now xfcolorize executes smoothly.

The background still doesn't change though but that can be fixed manually.

**Comment by reorr** [comment]
please try the 1.2.3 version, the wallpaper should changed automatically now.
